server:
  port: 8095

spring:
  application:
    name: appointment-booking-backend
  datasource:
    url: jdbc:mysql://localhost:3306/appointment?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: mySecretKeyForJwtTokenGenerationThatIsAtLeast256BitsLongForHS256
    expiration-ms: 86400000
  slot-generation:
    days-ahead: 60
